version: '3.9'

services:
  postgres-database:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: klockandb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - klockan-network

  klockan-backend:
    container_name: backend-container
    image: klockan-backend:v1
    build: .
    ports:
      - 5209:8080
    depends_on:
      - postgres-database
    networks:
      - klockan-network

volumes:
  postgres_data:

networks:
  klockan-network:
    driver: bridge